# Generated by Django 2.2.3 on 2019-08-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20190802_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, max_length=60)),
                ('terpene_type', models.CharField(blank=True, max_length=60)),
                ('thc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cbd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_for', models.CharField(blank=True, max_length=60)),
                ('sold', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('cartridge_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ct_name', to='supply.Cartridge')),
                ('distillate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dist_name', to='supply.Distillate')),
            ],
        ),
    ]
