# Generated by Django 2.2.3 on 2019-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_name', models.CharField(blank=True, max_length=60)),
                ('battery_model', models.CharField(blank=True, max_length=60)),
                ('battery_type', models.CharField(blank=True, max_length=60)),
                ('mah', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sourced_from', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True, help_text='battery review', null=True)),
            ],
        ),
    ]
